version: '3.8'

services:
  apirest:
    container_name: apirest
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - mongodbwsp
    volumes:
      - .:/usr/src/app
    networks:
      - mired
  mongodbwsp:
    container_name: mongodbwsp
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mired

networks:
  mired:
    driver: bridge
    